// AUTO-GENERATED from Relicsol case-study source files. Text preserved verbatim.
export type CaseStudyStat = { value: string; label: string };
export type CaseStudyOverview = {
  client: string;
  industry: string;
  location: string;
  year: string;
  services: string;
};

export type CaseStudy = {
  slug: string;
  displayId: string;
  name: string;
  breadcrumbName: string;
  heroTags: string[];
  headline: string;
  headlineAccent: string;
  heroDescription: string;
  overview: CaseStudyOverview;
  challenge: { label: string; heading: string; paragraphs: string[] };
  approach: { label: string; heading: string; paragraphs: string[] };
  quote: { text: string; attribution: string };
  result: { label: string; heading: string; stats: CaseStudyStat[] };
  techTags: string[];
  nextSlug: string;
  bgGradient: string;
  image: string;
  category: string;
};

export const caseStudies: CaseStudy[] = [
  {
    slug: `saki-products`,
    displayId: `01`,
    name: `Saki Products`,
    breadcrumbName: `SAKI PRODUCTS`,
    heroTags: [`E-Commerce`, `Product Design`, `Shopify`],
    headline: `Saki Products — Smart kitchen, premium experience.`,
    headlineAccent: `experience.`,
    heroDescription: `Premium product-page architecture and conversion-focused commerce for a US smart-kitchen appliance brand competing at the high end.`,
    overview: {
      client: `Saki Products`,
      industry: `Smart Appliances`,
      location: `USA`,
      year: `2024`,
      services: `E-com · UX · CRO`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Premium products, undersold by their own commerce.`,
      paragraphs: [`Saki manufactures premium smart kitchen appliances — coffee makers, egg cookers, kitchen tools — competing with Breville and Cuisinart at a higher design standard.`, `The existing product pages were functional but did not communicate the premium positioning or justify the price point to a discerning American consumer.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Product-first commerce. Story before sale.`,
      paragraphs: [`We built a product-first commerce experience where each page tells a story before asking for a purchase. Hero videos, lifestyle photography callouts, comparison tables, and review integration build desire before the add-to-cart moment.`, `Architecture on Shopify with custom sections for maximum flexibility. The mobile checkout was streamlined for impulse-purchase behaviour common in the premium appliance category.`],
    },
    quote: {
      text: `The new site finally gives our products the room to breathe. Customers stay on the page, read the story, and convert.`,
      attribution: `— SAKI PRODUCTS, US BRAND TEAM`,
    },
    result: {
      label: `03 / The Result`,
      heading: `A product page that performs like a brand campaign.`,
      stats: [
        { value: `+34%`, label: `Product page conversion rate` },
        { value: `+22%`, label: `Average order value` },
        { value: `91/100`, label: `Mobile PageSpeed score` },
      ],
    },
    techTags: [`Shopify`, `Custom Liquid`, `Section Architecture`, `PageSpeed`, `Klaviyo`],
    nextSlug: `loiseau-2`,
    bgGradient: `linear-gradient(135deg,#064e3b,#022c22)`,
    image: `/images/sakiproducts.webp`,
    category: `e-commerce`,
  },
  {
    slug: `push-digital-group`,
    displayId: `02`,
    name: `Push Digital Group`,
    breadcrumbName: `PUSH DIGITAL GROUP`,
    heroTags: [`Corporate`, `Web Design`, `WordPress`],
    headline: `Push Digital Group — A political agency site built for authority.`,
    headlineAccent: `authority.`,
    heroDescription: `Editorial dark typography and a case-study architecture that finally matched the scale of the campaigns Push Digital runs across the United States.`,
    overview: {
      client: `Push Digital Group`,
      industry: `Political Agency`,
      location: `USA`,
      year: `2024`,
      services: `Web · WP · SEO`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `A national political agency with a website that did not match the work.`,
      paragraphs: [`Push Digital Group is one of the USA's leading political digital agencies, working with major campaigns, PACs, and political organisations across the country. Their existing website did not reflect the scale, sophistication, or authority of their work.`, `It looked like an agency that ran local campaigns, not one trusted with high-stakes national political strategy. They needed a site that communicated credibility immediately and converted high-value political clients.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Typography-led dark editorial. Closer to a media company than a typical agency.`,
      paragraphs: [`We designed a typography-led dark website that feels editorial and authoritative. Bold serif-adjacent headlines, heavy contrast, and a case-study architecture that led visitors through the depth of Push Digital's campaign work.`, `The conversion path was structured to generate direct consultation requests from qualified political clients. Tech stack: WordPress with a fully custom theme, Elementor Pro for content blocks the team could maintain, Cloudflare for delivery, and a hardened on-page SEO foundation across every template.`],
    },
    quote: {
      text: `First time our website actually felt like us. We get on calls now and clients are already pre-sold by the time we pick up the phone.`,
      attribution: `— PUSH DIGITAL GROUP LEADERSHIP`,
    },
    result: {
      label: `03 / The Result`,
      heading: `A site that earns trust before the first sentence is read.`,
      stats: [
        { value: `94/100`, label: `Mobile PageSpeed score` },
        { value: `+48%`, label: `Qualified lead inquiry rate` },
        { value: `3wks`, label: `Delivered on time and on budget` },
      ],
    },
    techTags: [`WordPress`, `Custom Theme`, `Elementor Pro`, `On-Page SEO`, `Cloudflare`],
    nextSlug: `loiseau-2`,
    bgGradient: `linear-gradient(135deg,#1e293b,#0f172a)`,
    image: `/images/pushdigital.webp`,
    category: `corporate`,
  },
  {
    slug: `loiseau-2`,
    displayId: `03`,
    name: `L'Oiseau De`,
    breadcrumbName: `L'OISEAU DE`,
    heroTags: [`E-Commerce`, `Luxury Beauty`, `WooCommerce`],
    headline: `L'Oiseau De — Luxury beauty built for the European market.`,
    headlineAccent: `European market.`,
    heroDescription: `Editorial WooCommerce for a premium cosmetics brand that needed a platform as refined as the photography.`,
    overview: {
      client: `L'Oiseau De`,
      industry: `Luxury Cosmetics`,
      location: `Europe`,
      year: `2024`,
      services: `E-com · Theme · UX`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `A luxury brand on a templated platform.`,
      paragraphs: [`L'Oiseau De is a premium cosmetics brand targeting the European luxury market. The challenge was building a commerce experience that matched the brand positioning — not just a Shopify template with a logo dropped in.`, `The product photography was high quality. The platform needed to amplify it, not compete with it.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `WooCommerce, custom theme, editorial pacing.`,
      paragraphs: [`We built the platform on WooCommerce with a fully custom theme designed around the brand's visual identity. Fluid page transitions, generous whitespace, and product page architecture that led customers through ingredient stories before the purchase decision.`, `The checkout flow was streamlined to reduce abandonment on mobile, and the product photography was given the editorial space it deserved at every breakpoint.`],
    },
    quote: {
      text: `Finally a website that feels like our products. Our customers tell us this on the first visit.`,
      attribution: `— L'OISEAU DE, BRAND TEAM`,
    },
    result: {
      label: `03 / The Result`,
      heading: `A platform that earned editorial coverage at launch.`,
      stats: [
        { value: `+2.8min`, label: `Average session duration increase` },
        { value: `+31%`, label: `Mobile conversion rate` },
        { value: `2`, label: `European beauty editorial features` },
      ],
    },
    techTags: [`WordPress`, `WooCommerce`, `Custom Theme`, `Fluid Animations`, `Cloudflare CDN`],
    nextSlug: `firmate`,
    bgGradient: `linear-gradient(135deg,#7c2d12,#431407)`,
    image: `/images/loiseau.webp`,
    category: `e-commerce`,
  },
  {
    slug: `nextsense`,
    displayId: `04`,
    name: `Nextsense`,
    breadcrumbName: `NEXTSENSE`,
    heroTags: [`Health Tech`, `Product`, `Next.js`],
    headline: `NextSense — The world's first EEG earbuds, presented at full ambition.`,
    headlineAccent: `full ambition.`,
    heroDescription: `A dark cinematic Next.js product site speaking to researchers, investors, and consumers in a single narrative arc.`,
    overview: {
      client: `NextSense`,
      industry: `Health Tech`,
      location: `USA`,
      year: `2024`,
      services: `Web · Next.js · UX`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `A category-defining product, two very different audiences.`,
      paragraphs: [`NextSense is developing the world's first EEG earbuds — a genuinely category-defining health-tech product. The challenge was presenting deep science to two audiences at once.`, `Researchers and investors need clinical depth. Consumers need to understand why they would wear these in daily life. One site had to speak to both.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `A single narrative arc, two reading paths.`,
      paragraphs: [`We built a dark cinematic Next.js site with a clear narrative arc — starting with the emotional "imagine" hook for consumers, moving into the clinical science for credibility, and landing in a research partnership and waitlist CTA.`, `Scroll-triggered animations revealed content in sequence that matched the storytelling. The design leaned into the health-tech dark aesthetic — precise, scientific, premium — without sacrificing accessibility on either content track.`],
    },
    quote: {
      text: `This is the first site that actually feels like the product we are building. Researchers and consumers respond to it.`,
      attribution: `— NEXTSENSE TEAM`,
    },
    result: {
      label: `03 / The Result`,
      heading: `Research inquiries and waitlist signals that exceeded targets.`,
      stats: [
        { value: `3`, label: `Research partnerships in month one` },
        { value: `+40%`, label: `Waitlist sign-ups above target` },
        { value: `2`, label: `Health tech publication features` },
      ],
    },
    techTags: [`Next.js`, `Framer Motion`, `Tailwind`, `Vercel`, `Scroll Anim`],
    nextSlug: `forerunners-group`,
    bgGradient: `linear-gradient(135deg,#1e3a8a,#0c1e3e)`,
    image: `/images/nextsense.webp`,
    category: `saas`,
  },
  {
    slug: `forerunners-group`,
    displayId: `05`,
    name: `Forerunners Group`,
    breadcrumbName: `FORERUNNERS GROUP`,
    heroTags: [`Corporate`, `Consulting`, `WordPress`],
    headline: `Forerunners Group — Authority and trust, built into every page.`,
    headlineAccent: `built into every page.`,
    heroDescription: `An enterprise consulting site that converts boardroom-level traffic into qualified consultations.`,
    overview: {
      client: `Forerunners Group`,
      industry: `Consulting`,
      location: `USA`,
      year: `2024`,
      services: `Web · WP · Lead Gen`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Crowded market, trust is everything.`,
      paragraphs: [`Forerunners Group is a business automation and analytics consultancy helping mid-market companies extract value from data using Power BI, Tableau, and Google Cloud.`, `The consulting market is crowded and trust is everything. Their website needed to immediately communicate expertise and generate qualified enterprise leads.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Thought leadership first. Services second.`,
      paragraphs: [`We built an authority-first site architecture. Thought leadership content front and center. Service definitions framed around business outcomes rather than technical deliverables.`, `The case study section spoke in revenue impact, not deliverable lists. Lead generation flow was structured around a free consultation with clear qualification criteria, filtering out tire-kickers before they reached the calendar.`],
    },
    quote: {
      text: `We can finally point to our website in a sales conversation. It does part of the convincing for us.`,
      attribution: `— FORERUNNERS GROUP, LEADERSHIP`,
    },
    result: {
      label: `03 / The Result`,
      heading: `Enterprise leads that close, not just leads.`,
      stats: [
        { value: `+58%`, label: `Consultation request rate` },
        { value: `2`, label: `Enterprise accounts in first 90 days` },
        { value: `+44%`, label: `Average lead quality score` },
      ],
    },
    techTags: [`WordPress`, `Custom Theme`, `On-Page SEO`, `Lead Gen Forms`, `Cloudflare`],
    nextSlug: `house-wine`,
    bgGradient: `linear-gradient(135deg,#374151,#111827)`,
    image: `/images/forerunnersgroup.webp`,
    category: `corporate`,
  },
  {
    slug: `house-wine`,
    displayId: `06`,
    name: `House Wine`,
    breadcrumbName: `HOUSE WINE`,
    heroTags: [`E-Commerce`, `Marketplace`, `WooCommerce`],
    headline: `House Wine — A marketplace as refined as the wines it sells.`,
    headlineAccent: `wines it sells.`,
    heroDescription: `A multi-vendor European wine marketplace with Dutch design sensibility and AI-assisted cellar management.`,
    overview: {
      client: `House Wine`,
      industry: `Wine Marketplace`,
      location: `Netherlands`,
      year: `2024`,
      services: `Platform · UX · AI`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Independent wines on a generic store.`,
      paragraphs: [`House Wine is an independent wine marketplace connecting small estates, sellers, and collectors across Europe. The existing platform looked like a generic WooCommerce store.`, `The challenge was building something that felt as curated and refined as the wines themselves — while handling the operational complexity of a multi-vendor marketplace.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Earthy Dutch design and discovery by mood.`,
      paragraphs: [`We built a custom WooCommerce marketplace with an earthy, sophisticated Dutch design language. Muted earth tones, generous whitespace, producer story pages, and a discovery architecture that helped buyers find bottles by mood, occasion, and food pairing — not just variety and vintage.`, `We added a basic AI cellar management feature that helped users track and plan their collection — a differentiator no other Dutch wine marketplace offers.`],
    },
    quote: {
      text: `The discovery flow is the part that surprises everyone. Buyers stay longer and buy bottles they did not know to look for.`,
      attribution: `— HOUSE WINE FOUNDER`,
    },
    result: {
      label: `03 / The Result`,
      heading: `A platform that scaled both supply and demand.`,
      stats: [
        { value: `+45%`, label: `Seller onboarding rate post-launch` },
        { value: `+2.8min`, label: `Average session duration increase` },
        { value: `1`, label: `Dutch food and wine press feature` },
      ],
    },
    techTags: [`WordPress`, `WooCommerce`, `Multi-Vendor`, `AI Cellar`, `Dutch SEO`],
    nextSlug: `firmate`,
    bgGradient: `linear-gradient(135deg,#3f2418,#1c0f08)`,
    image: `/images/housewine.webp`,
    category: `e-commerce`,
  },
  {
    slug: `firmate`,
    displayId: `07`,
    name: `Firmate`,
    breadcrumbName: `FIRMATE`,
    heroTags: [`SaaS`, `Landing Page`, `Next.js`],
    headline: `Firmate — A SaaS landing page built to convert trials.`,
    headlineAccent: `convert trials.`,
    heroDescription: `A vibrant Next.js landing page for an AI brand-identity tool competing against well-funded incumbents.`,
    overview: {
      client: `Firmate (firmate.io)`,
      industry: `SaaS · AI Tools`,
      location: `USA`,
      year: `2024`,
      services: `Landing · Next.js · CRO`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Crowded AI tools market, free trial conversion.`,
      paragraphs: [`Firmate is an AI-powered platform that generates brand identities — logos, color systems, typography, and brand guidelines from a brief. In a crowded AI tools market, the landing page needed to do three things at once.`, `Communicate output quality immediately, lower the barrier to the free trial, and position Firmate against well-funded competitors — all above the first scroll.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Product output as hero. Five trial CTAs, five contexts.`,
      paragraphs: [`We designed a bold gradient-forward landing page that showcased the product's output quality front and center. The hero led with a live example output, not feature descriptions.`, `Social proof — reviews, usage numbers, press — was placed immediately after the hero. The free trial CTA appeared five times in the page, each with a different motivating context tailored to where the visitor was in the page.`],
    },
    quote: {
      text: `The new site is doing the heavy lifting in fundraising conversations. Investors get it the moment they land.`,
      attribution: `— FIRMATE FOUNDER`,
    },
    result: {
      label: `03 / The Result`,
      heading: `Conversion lift big enough to redirect the ad budget.`,
      stats: [
        { value: `+41%`, label: `Free trial conversion rate` },
        { value: `-28%`, label: `Bounce rate reduction` },
        { value: `Used`, label: `In investor funding conversations` },
      ],
    },
    techTags: [`Next.js`, `Tailwind`, `Framer Motion`, `Vercel`, `Conversion arch`],
    nextSlug: `farm-minerals`,
    bgGradient: `linear-gradient(135deg,#4c1d95,#1e1b4b)`,
    image: `/images/firmate.webp`,
    category: `saas`,
  },
  {
    slug: `farm-minerals`,
    displayId: `08`,
    name: `Farm Minerals`,
    breadcrumbName: `FARM MINERALS`,
    heroTags: [`AgTech`, `Product`, `WordPress`],
    headline: `Farm Minerals CropTab — Revolutionary AgTech at investor quality.`,
    headlineAccent: `investor quality.`,
    heroDescription: `A dark editorial site for a carbon-capsule fertilizer tablet, dual-targeted at farmers and AgTech investors.`,
    overview: {
      client: `Farm Minerals`,
      industry: `AgTech`,
      location: `USA / AU`,
      year: `2024`,
      services: `Web · Brand · SEO`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Revolutionary product, two very different audiences.`,
      paragraphs: [`CropTab is a carbon-capsule fertilizer tablet that delivers precision nutrition while capturing carbon — a genuinely revolutionary product in the AgTech space.`, `The challenge was a site that worked for farmers who needed practical crop benefits and for investors and institutions who needed to see science and market opportunity. The brief was Bloomberg-grade presentation on a farming product.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Dark editorial. Cinematic field photography. Two narrative tracks.`,
      paragraphs: [`We built a dark editorial site that felt premium and scientific. The hero led with the environmental impact story. Subsequent sections moved between farming benefits (yield improvement, ease of application) and the investor narrative (carbon credit mechanism, market size, regulatory tailwinds).`, `Photography of fields and close-up product shots. Editorial typography. The site was used successfully in an investor pitch round shortly after launch.`],
    },
    quote: {
      text: `Investors read it in five minutes and understood the opportunity. That is the conversion we were chasing.`,
      attribution: `— FARM MINERALS LEADERSHIP`,
    },
    result: {
      label: `03 / The Result`,
      heading: `A site that worked in a pitch room and on a farm.`,
      stats: [
        { value: `+67%`, label: `Distributor inquiry rate` },
        { value: `Success`, label: `Investor pitch round supported` },
        { value: `1`, label: `AgTech industry newsletter citation` },
      ],
    },
    techTags: [`WordPress`, `Custom Theme`, `Editorial DS`, `SEO`, `Cloudflare`],
    nextSlug: `evanlite`,
    bgGradient: `linear-gradient(135deg,#365314,#1a2e05)`,
    image: `/images/farmminerals.webp`,
    category: `agtech`,
  },
  {
    slug: `evanlite`,
    displayId: `09`,
    name: `Evanlite`,
    breadcrumbName: `EVANLITE`,
    heroTags: [`E-Commerce`, `Sports`, `WooCommerce`],
    headline: `Evanlite — 25 years of carbon expertise, online at full quality.`,
    headlineAccent: `full quality.`,
    heroDescription: `A dark performance commerce site for a heritage carbon cycling wheel brand, with a discipline-based configurator.`,
    overview: {
      client: `Evanlite`,
      industry: `Cycling Performance`,
      location: `Europe`,
      year: `2024`,
      services: `E-com · Config · UX`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Heritage brand, modest digital presence.`,
      paragraphs: [`Evanlite has been handcrafting premium carbon cycling wheels for 25+ years — a heritage brand with exceptional product quality but a digital presence that did not reflect either the price point or the expertise.`, `Competitive cyclists comparing carbon wheels at ——2,000+ per set need deep technical data and a site that builds trust through specificity, not marketing copy.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Dark, technical, configurable.`,
      paragraphs: [`We built a dark, product-led commerce site with a model explorer that lets cyclists configure wheels by discipline (road, triathlon, gravel), rim depth, and hub specification.`, `Technical specifications were presented as design tiles rather than spec tables. Verified-purchase reviews were integrated prominently. The mobile experience was tuned for at-event browsing, where most enthusiast research happens.`],
    },
    quote: {
      text: `Best online quarter we have ever had. The configurator is doing what our sales team used to do on the phone.`,
      attribution: `— EVANLITE TEAM`,
    },
    result: {
      label: `03 / The Result`,
      heading: `Heritage trust, modern commerce.`,
      stats: [
        { value: `+52%`, label: `International inquiry rate` },
        { value: `Best`, label: `Online sales quarter following launch` },
        { value: `Higher`, label: `Repeat buyer rate with configurator` },
      ],
    },
    techTags: [`WooCommerce`, `Config Tool`, `Product Photo`, `EU SEO`, `Stripe`],
    nextSlug: `core-atelier-pilates`,
    bgGradient: `linear-gradient(135deg,#27272a,#09090b)`,
    image: `/images/evanlite.webp`,
    category: `e-commerce`,
  },
  {
    slug: `core-atelier-pilates`,
    displayId: `10`,
    name: `Core Atelier`,
    breadcrumbName: `CORE ATELIER`,
    heroTags: [`Wellness`, `Luxury`, `WordPress`],
    headline: `Core Atelier — A luxury studio site that attracts the right clients.`,
    headlineAccent: `right clients.`,
    heroDescription: `A warm editorial site for an elevated pilates studio, converting affluent local discovery into bookings.`,
    overview: {
      client: `Core Atelier`,
      industry: `Luxury Fitness`,
      location: `UK`,
      year: `2024`,
      services: `Web · Booking · Local SEO`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Premium studio, gym-template website.`,
      paragraphs: [`Core Atelier is an elevated pilates studio targeting high-value wellness clients. The previous site looked like a generic gym website — stock photos, cluttered layout, no clear premium signal.`, `The studio was filling classes through word of mouth but the website was not converting online discovery into bookings, especially from a wealthy demographic looking for a premium experience.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Warm, editorial, three-step booking.`,
      paragraphs: [`We built a warm refined website using editorial photography the studio already had. Large format images, generous whitespace, a subtle warm palette, and copy that spoke to transformation rather than exercise.`, `The booking flow was integrated with Mindbody and simplified to three steps. Local SEO was configured for the studio's neighbourhood and surrounding affluent areas.`],
    },
    quote: {
      text: `Our new clients arrive already feeling like they belong here. The site does the qualifying for us.`,
      attribution: `— CORE ATELIER FOUNDER`,
    },
    result: {
      label: `03 / The Result`,
      heading: `Online discovery turned into the strongest acquisition channel.`,
      stats: [
        { value: `+63%`, label: `Online booking rate` },
        { value: `Higher`, label: `Avg new client first-month value` },
        { value: `60 days`, label: `Maps ranking improved for target area` },
      ],
    },
    techTags: [`WordPress`, `Mindbody`, `Local SEO`, `Photography`, `Cloudflare`],
    nextSlug: `drink-pouch`,
    bgGradient: `linear-gradient(135deg,#78350f,#3a1d05)`,
    image: `/images/coreatelierpilates.webp`,
    category: `wellness`,
  },
  {
    slug: `drink-pouch`,
    displayId: `11`,
    name: `Drink Pouch`,
    breadcrumbName: `DRINK POUCH`,
    heroTags: [`E-Commerce`, `Health Bev`, `Shopify`],
    headline: `Drink Pouch — A performance brand that hits hard online.`,
    headlineAccent: `hard online.`,
    heroDescription: `A bold dark Shopify commerce experience for a US performance-hydration brand competing in a crowded supplement market.`,
    overview: {
      client: `Drink Pouch`,
      industry: `Health Beverage`,
      location: `USA`,
      year: `2024`,
      services: `E-com · Subs · CRO`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Crowded US supplement market, instant-purchase intent.`,
      paragraphs: [`Drink Pouch is a premium performance hydration brand using IV-formula electrolyte science in a convenient pouch format. The US supplement market is intensely competitive — with Liquid IV and LMNT dominating awareness.`, `Drink Pouch needed a site that immediately communicated premium science positioning while converting high-intent buyers on the first visit, especially on mobile.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Bold dark performance commerce, subscription-first.`,
      paragraphs: [`We designed a bold dark e-commerce experience that leaned into the performance/sports aesthetic. Dramatic product photography, ingredient callouts with clinical backing, and subscription offer architecture designed to convert single purchases to recurring revenue.`, `The mobile checkout was streamlined for impulse-purchase behaviour common in the supplement category. The post-purchase sequence is automated to drive review collection and second orders.`],
    },
    quote: {
      text: `The subscription conversion alone paid for the rebuild in the first quarter.`,
      attribution: `— DRINK POUCH FOUNDER`,
    },
    result: {
      label: `03 / The Result`,
      heading: `Subscription growth that changed the unit economics.`,
      stats: [
        { value: `Exceeded`, label: `90-day subscription targets` },
        { value: `+38%`, label: `Mobile add-to-cart rate` },
        { value: `1`, label: `US health supplement newsletter feature` },
      ],
    },
    techTags: [`Shopify`, `Custom Liquid`, `Subscription`, `Bold Commerce`, `PageSpeed`],
    nextSlug: `wordpress-theme-development`,
    bgGradient: `linear-gradient(135deg,#0c4a6e,#082f49)`,
    image: `/images/drinkpouch.webp`,
    category: `e-commerce`,
  },
  {
    slug: `wordpress-theme-development`,
    displayId: `12`,
    name: `Sophia Pro`,
    breadcrumbName: `SOPHIA PRO`,
    heroTags: [`Software`, `WordPress`, `Theme Dev`],
    headline: `Sophia Pro — A WordPress theme built for real business needs.`,
    headlineAccent: `real business needs.`,
    heroDescription: `A multi-purpose theme with custom blocks, ACF templates, and Elementor compatibility — built for service businesses.`,
    overview: {
      client: `Sophia Pro (Internal)`,
      industry: `WordPress Theme`,
      location: `Global`,
      year: `2024`,
      services: `Theme · Blocks · WooCommerce`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `A theme for businesses, not designers.`,
      paragraphs: [`The brief was to build a premium multi-purpose WordPress theme that service businesses could use without needing a developer for routine customisation.`, `The theme had to handle services, portfolios, team pages, testimonials, and WooCommerce — all within a cohesive design system that did not require Elementor expertise to maintain.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Custom theme + custom blocks + ACF templates.`,
      paragraphs: [`We built a fully custom theme with a custom Gutenberg block library, ACF-based page templates, and a WooCommerce skin. Elementor Pro compatibility was built in for users who preferred that workflow, but the theme worked fully without it.`, `The design system was documented and the admin panel included basic customisation controls for colors, typography, and layout — so non-technical owners could rebrand the entire site without code.`],
    },
    quote: {
      text: `Six months of client work later and we have not opened a support ticket. The theme just works.`,
      attribution: `— INTERNAL TEAM`,
    },
    result: {
      label: `03 / The Result`,
      heading: `A theme that cut delivery time in half.`,
      stats: [
        { value: `-40%`, label: `Site delivery time on projects` },
        { value: `Multiple`, label: `Client sites deployed` },
        { value: `0`, label: `Major support tickets in 6 months` },
      ],
    },
    techTags: [`WordPress`, `PHP`, `ACF`, `Gutenberg`, `WooCommerce`, `Elementor`],
    nextSlug: `yucca-packaging`,
    bgGradient: `linear-gradient(135deg,#1e1b4b,#0a0a1f)`,
    image: `/images/wpcustomthemes.webp`,
    category: `software`,
  },
  {
    slug: `yucca-packaging`,
    displayId: `13`,
    name: `Yucca Packaging`,
    breadcrumbName: `YUCCA PACKAGING`,
    heroTags: [`B2B`, `Packaging`, `WordPress`],
    headline: `Yucca Packaging — B2B credibility built into every page.`,
    headlineAccent: `every page.`,
    heroDescription: `A clean editorial B2B site for a packaging supplier, with category-first navigation and credit application integration.`,
    overview: {
      client: `Yucca Packaging`,
      industry: `B2B Packaging`,
      location: `South Africa`,
      year: `2024`,
      services: `Web · B2B · Forms`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Procurement audience, no time for marketing-speak.`,
      paragraphs: [`Yucca Packaging supplies food service packaging to restaurants, caterers, and food manufacturers across South Africa and internationally.`, `Their buyers are procurement managers and operations directors — a professional B2B audience who need product specifications, certifications, and easy ordering, not a flashy consumer experience.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Category navigation, spec sheets, fewer clicks to quote.`,
      paragraphs: [`We built a clean, product-category-first website where buyers could navigate directly to their packaging category, find specification sheets, and submit credit applications or product inquiries without friction.`, `The design was professional without being corporate — warm enough to feel like a genuine business partner rather than a faceless supplier, and structured to make repeat ordering frictionless.`],
    },
    quote: {
      text: `Our credit application completion rate is the biggest jump we have seen from a website project. That number is gold.`,
      attribution: `— YUCCA PACKAGING LEADERSHIP`,
    },
    result: {
      label: `03 / The Result`,
      heading: `A B2B site that respected the buyer's time.`,
      stats: [
        { value: `+44%`, label: `Inquiry-to-quote conversion rate` },
        { value: `+71%`, label: `Credit application completion rate` },
        { value: `+35%`, label: `International buyer inquiries` },
      ],
    },
    techTags: [`WordPress`, `WooCommerce`, `PDF Integration`, `Multi-currency`, `SEO`],
    nextSlug: `silberthal`,
    bgGradient: `linear-gradient(135deg,#475569,#1e293b)`,
    image: `/images/yucca.webp`,
    category: `corporate`,
  },
  {
    slug: `silberthal`,
    displayId: `14`,
    name: `Silberthal`,
    breadcrumbName: `SILBERTHAL`,
    heroTags: [`E-Commerce`, `Kitchenware`, `WooCommerce`],
    headline: `Silberthal — 1.1 million European customers deserve a site that matches.`,
    headlineAccent: `matches.`,
    heroDescription: `A photography-led WooCommerce experience built around the 100-day trial guarantee and 1.1M customer trust signal.`,
    overview: {
      client: `Silberthal`,
      industry: `Premium Kitchenware`,
      location: `Germany`,
      year: `2024`,
      services: `E-com · Trust · DE SEO`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Trusted brand, underexpressed online.`,
      paragraphs: [`Silberthal is a premium German kitchenware brand trusted by over 1.1 million customers across Europe. The brand quality was unquestionable but the online store did not communicate that trust to new visitors.`, `In particular, the 100-day trial guarantee — a significant competitive differentiator in the premium cookware market — was nearly invisible on the existing site.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Photography, social proof, the guarantee on every page.`,
      paragraphs: [`We rebuilt the e-commerce experience around photography and trust signals. The 100-day trial guarantee appeared prominently on every product page. Customer review volume (1.1M+ customers) was surfaced in the hero.`, `Product pages were restructured to lead with beauty imagery, move into material quality and craftsmanship details, and close with social proof. The German market SEO was rebuilt for the priority product categories.`],
    },
    quote: {
      text: `New customers reach the product page already trusting us. Return rates dropped because expectations are set correctly.`,
      attribution: `— SILBERTHAL TEAM`,
    },
    result: {
      label: `03 / The Result`,
      heading: `Trust that scaled across 1.1M customers.`,
      stats: [
        { value: `Reduced`, label: `Product return rate post-redesign` },
        { value: `Improved`, label: `Trust-to-trial conversion rate` },
        { value: `90 days`, label: `German SEO rankings improved` },
      ],
    },
    techTags: [`WooCommerce`, `Photo Layout`, `GDPR`, `DE Market SEO`, `Reviews`],
    nextSlug: `strategic-gears`,
    bgGradient: `linear-gradient(135deg,#292524,#0c0a09)`,
    image: `/images/silberthal.webp`,
    category: `e-commerce`,
  },
  {
    slug: `strategic-gears`,
    displayId: `15`,
    name: `Strategic Gears`,
    breadcrumbName: `STRATEGIC GEARS`,
    heroTags: [`Corporate`, `Consulting`, `Multilingual`],
    headline: `Strategic Gears — Enterprise authority built into every pixel.`,
    headlineAccent: `every pixel.`,
    heroDescription: `A multilingual (EN/AR) enterprise consulting site with a thought-leadership hub and cinematic architectural photography.`,
    overview: {
      client: `Strategic Gears`,
      industry: `Management Consulting`,
      location: `UAE / MENA`,
      year: `2024`,
      services: `Multilingual · Editorial · SEO`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `A site that needed to carry weight in the boardroom.`,
      paragraphs: [`Strategic Gears is a UAE-based management consultancy advising enterprise clients across the MENA region. Their website needed to carry weight in boardroom conversations.`, `When a CEO googles them before a meeting, the site needed to immediately confirm that Strategic Gears operates at the same level as the world's top consultancies — without any of the templated feel that plagues most consulting sites.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Cinematic editorial, deep thought-leadership hub.`,
      paragraphs: [`We built a cinematic, architecture-photography-led site with a deep thought leadership content hub. Insight articles, white papers, and point-of-view content were structured to demonstrate expertise rather than list services.`, `The multilingual architecture (English and Arabic with full RTL support) was built into the core rather than added as an afterthought, including a complete RTL design system for the Arabic experience.`],
    },
    quote: {
      text: `Our partners use the site in joint pitches. It signals what we want it to signal before we say a word.`,
      attribution: `— STRATEGIC GEARS LEADERSHIP`,
    },
    result: {
      label: `03 / The Result`,
      heading: `A site that performs in pitch rooms across the region.`,
      stats: [
        { value: `Increased`, label: `Enterprise RFP inquiry rate` },
        { value: `Consistent`, label: `Organic traffic growth from hub` },
        { value: `Used`, label: `In partnership presentations` },
      ],
    },
    techTags: [`WordPress`, `WPML`, `Editorial CMS`, `Arabic RTL`, `Enterprise SEO`],
    nextSlug: `the-trend-chartist`,
    bgGradient: `linear-gradient(135deg,#0f172a,#020617)`,
    image: `/images/strategicgears.webp`,
    category: `corporate`,
  },
  {
    slug: `the-trend-chartist`,
    displayId: `16`,
    name: `The Trend Chartist`,
    breadcrumbName: `THE TREND CHARTIST`,
    heroTags: [`Education`, `Finance`, `MemberPress`],
    headline: `The Trend Chartist — Education for serious researchers.`,
    headlineAccent: `serious researchers.`,
    heroDescription: `A clean editorial platform for technical analysis education with a research library and freemium-to-paid funnel.`,
    overview: {
      client: `The Trend Chartist`,
      industry: `Financial Education`,
      location: `USA`,
      year: `2024`,
      services: `Web · Members · Newsletter`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Growing research library, no architecture.`,
      paragraphs: [`The Trend Chartist provides technical analysis education and stock market research to a subscriber base of serious traders and investors.`, `The platform needed to organise a growing library of research articles, courses, and market updates into something navigable — while converting free readers into paid subscribers.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Content-architecture first. Three-touch newsletter funnel.`,
      paragraphs: [`We built a content-architecture-first platform with a research library, article indexing by sector and methodology, and a clear freemium-to-paid conversion funnel.`, `The newsletter integration captured email at three points in the reader journey. The design was clean and editorial — appropriate for a financial audience that values signal over noise, with monospace data callouts and editorial article pages.`],
    },
    quote: {
      text: `Time-on-site went up and our paid conversion improved without changing the offer. The architecture is doing the work.`,
      attribution: `— THE TREND CHARTIST`,
    },
    result: {
      label: `03 / The Result`,
      heading: `A platform that scaled subscribers and engagement together.`,
      stats: [
        { value: `+89%`, label: `Newsletter subscriber growth rate` },
        { value: `+4.2min`, label: `Average time on site increase` },
        { value: `Improved`, label: `Paid subscription conversion rate` },
      ],
    },
    techTags: [`WordPress`, `MemberPress`, `Mailchimp`, `Taxonomy`, `Finance SEO`],
    nextSlug: `the-unleashed-heart`,
    bgGradient: `linear-gradient(135deg,#164e63,#083344)`,
    image: `/images/thetrendchartist.webp`,
    category: `education`,
  },
  {
    slug: `the-unleashed-heart`,
    displayId: `17`,
    name: `The Unleashed Heart`,
    breadcrumbName: `THE UNLEASHED HEART`,
    heroTags: [`Wellness`, `Coaching`, `Personal Brand`],
    headline: `The Unleashed Heart — Personal brand that earns trust before a word is read.`,
    headlineAccent: `word is read.`,
    heroDescription: `A warm personal-brand site for a certified grief recovery coach, structured around discovery-call conversion.`,
    overview: {
      client: `The Unleashed Heart`,
      industry: `Life Coaching`,
      location: `USA`,
      year: `2024`,
      services: `Personal Brand · Calendly · Comm`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Earn trust on first impression. Without feeling clinical or salesy.`,
      paragraphs: [`The coach is a certified grief recovery specialist working with people navigating loss, transition, and emotional recovery.`, `The website needed to achieve something difficult: earn deep emotional trust immediately, communicate genuine human warmth, and convert visitors into discovery call bookings — without feeling clinical, corporate, or salesy.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `The coach's own story, told first.`,
      paragraphs: [`We led with the coach's own story — her journey through grief and into coaching — before any service description. Photography was warm, personal, and real. The copy was written in the coach's own voice.`, `Community trust signals (8,300+ active community members, client transformation stories) were woven throughout. The discovery call CTA was positioned as a supportive conversation, not a sales call, lowering the emotional barrier to the click.`],
    },
    quote: {
      text: `My clients say they felt me on the website before we ever spoke. That is exactly what I wanted.`,
      attribution: `— THE UNLEASHED HEART FOUNDER`,
    },
    result: {
      label: `03 / The Result`,
      heading: `A site that did the emotional work upfront.`,
      stats: [
        { value: `+74%`, label: `Discovery call bookings` },
        { value: `+28%`, label: `Community membership growth` },
        { value: `Increased`, label: `Referral-based inquiry rate` },
      ],
    },
    techTags: [`WordPress`, `Calendly`, `Community`, `Copy Architecture`, `Local SEO`],
    nextSlug: `watchhouse`,
    bgGradient: `linear-gradient(135deg,#831843,#500724)`,
    image: `/images/theunleashedheart.webp`,
    category: `wellness`,
  },
  {
    slug: `watchhouse`,
    displayId: `18`,
    name: `WatchHouse`,
    breadcrumbName: `WATCHHOUSE`,
    heroTags: [`E-Commerce`, `Coffee`, `WooCommerce`],
    headline: `WatchHouse — Specialty coffee that deserves a site as good as the beans.`,
    headlineAccent: `beans.`,
    heroDescription: `A cinematic editorial brand site for one of London's finest specialty coffee roasters with subscription commerce.`,
    overview: {
      client: `WatchHouse Coffee`,
      industry: `Specialty Coffee`,
      location: `UK`,
      year: `2024`,
      services: `Brand · Subs · Multisite`,
    },
    challenge: {
      label: `01 / The Challenge`,
      heading: `Avoid every generic "artisan coffee" trope.`,
      paragraphs: [`WatchHouse is one of London's finest specialty coffee roasters, with multiple cafe locations and a growing online subscription business.`, `The challenge was building a site that honoured the brand's genuine craft positioning — not the generic "artisan" aesthetic that every third coffee brand uses, but something that felt as specific and considered as the beans themselves.`],
    },
    approach: {
      label: `02 / The Approach`,
      heading: `Split-screen editorial. Cafe and product, equal billing.`,
      paragraphs: [`We built a split-screen editorial hero that placed the roastery and the cafe in equal prominence — because WatchHouse is both a place and a product.`, `The subscription e-commerce was integrated with delivery scheduling and coffee preference profiles. Multi-location pages were built with individual character, not a template repeated five times — each cafe location got its own visual treatment.`],
    },
    quote: {
      text: `It looks and feels like our cafes look and feel. That is the highest compliment we can give a website.`,
      attribution: `— WATCHHOUSE TEAM`,
    },
    result: {
      label: `03 / The Result`,
      heading: `A site that earned a coverage piece at launch.`,
      stats: [
        { value: `Improved`, label: `Subscription sign-up rate` },
        { value: `Increased`, label: `In-store reservation rate` },
        { value: `1`, label: `UK specialty coffee press feature` },
      ],
    },
    techTags: [`WooCommerce`, `Subscriptions`, `Multisite`, `UK Local SEO`, `Editorial DS`],
    nextSlug: `push-digital-group`,
    bgGradient: `linear-gradient(135deg,#44403c,#0c0a09)`,
    image: `/images/watchhouse.webp`,
    category: `e-commerce`,
  },
];

export const caseStudyBySlug: Record<string, CaseStudy> = Object.fromEntries(
  caseStudies.map((c) => [c.slug, c])
);
